/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProcessService } from "../process.service";
import { ProcessCreateInput } from "./ProcessCreateInput";
import { ProcessWhereInput } from "./ProcessWhereInput";
import { ProcessWhereUniqueInput } from "./ProcessWhereUniqueInput";
import { ProcessFindManyArgs } from "./ProcessFindManyArgs";
import { ProcessUpdateInput } from "./ProcessUpdateInput";
import { Process } from "./Process";
import { MachineFindManyArgs } from "../../machine/base/MachineFindManyArgs";
import { Machine } from "../../machine/base/Machine";
import { MachineWhereUniqueInput } from "../../machine/base/MachineWhereUniqueInput";

export class ProcessControllerBase {
  constructor(protected readonly service: ProcessService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Process })
  async create(@common.Body() data: ProcessCreateInput): Promise<Process> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        meta: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Process] })
  @ApiNestedQuery(ProcessFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Process[]> {
    const args = plainToClass(ProcessFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        meta: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Process | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        meta: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() data: ProcessUpdateInput
  ): Promise<Process | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          meta: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Process })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Process | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          meta: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/machines")
  @ApiNestedQuery(MachineFindManyArgs)
  async findManyMachines(
    @common.Req() request: Request,
    @common.Param() params: ProcessWhereUniqueInput
  ): Promise<Machine[]> {
    const query = plainToClass(MachineFindManyArgs, request.query);
    const results = await this.service.findMachines(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        process: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/machines")
  async connectMachines(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: MachineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      machines: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/machines")
  async updateMachines(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: MachineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      machines: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/machines")
  async disconnectMachines(
    @common.Param() params: ProcessWhereUniqueInput,
    @common.Body() body: MachineWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      machines: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
